export const theme = {
  colors: {
    background: "#f4f7fb",
    white: "#ffffff",
    primary: "#2563eb",
    primaryDark: "#1d4ed8",
    text: "#111827",
    textMuted: "#6b7280",
    border: "#d1d5db",
    successBg: "#dcfce7",
    successText: "#166534",
    errorBg: "#fee2e2",
    errorText: "#b91c1c",
    danger: "#dc2626",
    dangerDark: "#b91c1c",
    grayBtn: "#e5e7eb",
  },
  shadow: "0 8px 24px rgba(0,0,0,0.08)",
};

export const sharedStyles = {
  authPage: {
    minHeight: "100vh",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "20px",
    background: "#f4f7fb",
  },
  authCard: {
    width: "100%",
    maxWidth: "420px",
    background: "#ffffff",
    padding: "30px",
    borderRadius: "16px",
    boxShadow: "0 8px 24px rgba(0,0,0,0.08)",
  },
  authHeader: {
    textAlign: "center",
    marginBottom: "20px",
  },
  authTitle: {
    margin: 0,
    fontSize: "28px",
    fontWeight: "700",
    color: "#111827",
  },
  authSubtitle: {
    marginTop: "8px",
    fontSize: "14px",
    color: "#6b7280",
  },
  input: {
    width: "100%",
    padding: "12px 14px",
    marginBottom: "12px",
    border: "1px solid #d1d5db",
    borderRadius: "10px",
    fontSize: "15px",
    boxSizing: "border-box",
    outline: "none",
    background: "#fff",
  },
  fileInput: {
    width: "100%",
    padding: "12px 14px",
    marginBottom: "12px",
    border: "1px dashed #9ca3af",
    borderRadius: "10px",
    fontSize: "15px",
    boxSizing: "border-box",
    background: "#f9fafb",
  },
  primaryButton: {
    width: "100%",
    padding: "12px",
    border: "none",
    borderRadius: "10px",
    background: "#2563eb",
    color: "#ffffff",
    fontWeight: "700",
    fontSize: "15px",
    cursor: "pointer",
  },
  secondaryButton: {
    padding: "10px 14px",
    border: "none",
    borderRadius: "10px",
    background: "#e5e7eb",
    color: "#111827",
    fontWeight: "600",
    cursor: "pointer",
  },
  dangerButton: {
    padding: "10px 14px",
    border: "none",
    borderRadius: "10px",
    background: "#dc2626",
    color: "#ffffff",
    fontWeight: "700",
    cursor: "pointer",
  },
  successBox: {
    marginBottom: "12px",
    padding: "10px 12px",
    borderRadius: "8px",
    background: "#dcfce7",
    color: "#166534",
    fontSize: "14px",
  },
  errorBox: {
    marginBottom: "12px",
    padding: "10px 12px",
    borderRadius: "8px",
    background: "#fee2e2",
    color: "#b91c1c",
    fontSize: "14px",
  },
  linkRow: {
    marginTop: "16px",
    display: "flex",
    justifyContent: "space-between",
    fontSize: "14px",
  },
  page: {
    minHeight: "100vh",
    background: "#f4f7fb",
    padding: "24px",
  },
  topbar: {
    background: "#ffffff",
    padding: "16px 20px",
    borderRadius: "14px",
    boxShadow: "0 8px 24px rgba(0,0,0,0.06)",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "24px",
    gap: "12px",
    flexWrap: "wrap",
  },
  topbarTitle: {
    margin: 0,
    fontSize: "24px",
    fontWeight: "700",
    color: "#111827",
  },
  pageCard: {
    background: "#ffffff",
    padding: "24px",
    borderRadius: "16px",
    boxShadow: "0 8px 24px rgba(0,0,0,0.08)",
  },
  pageTitle: {
    margin: 0,
    fontSize: "28px",
    fontWeight: "700",
    color: "#111827",
  },
  pageSubtitle: {
    margin: "6px 0 0 0",
    color: "#6b7280",
    fontSize: "14px",
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))",
    gap: "16px",
  },
  itemCard: {
    background: "#ffffff",
    padding: "18px",
    borderRadius: "14px",
    boxShadow: "0 8px 24px rgba(0,0,0,0.06)",
  },
};